### ISSUE TITLE
version 1.0.0 at windwos 11 22622.601 can not run

### ISSUE THREAD

**Issue by wintrue** [fluttertools/sidekick#256] opened 2022-09-26 08:40 UTC
![image](https://user-images.githubusercontent.com/6380530/192232021-18b51038-9d0a-4190-bf69-81e725666a64.png)

can not start app, not show APP

**Comment by aguilaair** [comment] 2022-09-27 20:52
Duplicate of #228

**Closed by aguilaair** 2022-09-27 20:52 UTC
